competition/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('spartakiada.urls')),
    path('', include('loging.urls')),
    path('admin/', admin.site.urls),
]

loging/urls.py
from django.conf.urls import url

from . import views
    
app_name = 'loging'

urlpatterns = [
    url(r'^register/$', views.UserCreateView.as_view(),
        name='register'),
    url(r'^login/$', views.UserLoginView.as_view(),
        name='login'),
    url(r'^logout/$', views.UserLogoutView.as_view(),
        name='logout')
]

spartakiada/urls.py
from django.conf.urls import url

from . import views

app_name = 'spartakiada'

urlpatterns = [
    url(r'^$', views.MenuView.as_view(),
        name='menu'),
    url(r'^about/', views.AboutView.as_view(),
        name='about'),
    url(r'^players/', views.PlayersView.as_view(),
        name='players'),
    url(r'^add_player/', views.PlayerAddView.as_view(),
        name='add-player'),
    url(r'^delete_player/', views.PlayerDeleteView.as_view(),
        name='delete-player'),
    url(r'^teams/', views.TeamsView.as_view(),
        name='teams'),
    url(r'^player_details/(?P<id>(\d)+)/$', views.PlayerDetailsView.as_view(),
        name='player'),
    url(r'^stats/$', views.Stats.as_view(),
        name='stats'),
    url(r'refresh_stats/$', views.refresh_stats,
        name='refresh-stats'),
    url(r'^add_team/', views.TeamAddView.as_view(),
        name='add-team'),
    url(r'^delete_teams/', views.TeamsDeleteView.as_view(),
        name='delete-teams'),
    url(r'^team_details/(?P<team_id>(\d)+)', views.TeamDetailsView.as_view(),
        name='team-details'),
    url(r'^team_add_members/(?P<team_id>(\d)+)', views.TeamAddMembersView.as_view(),
        name='team-add-members'),
    url(r'^team_remove_members/(?P<team_id>(\d)+)', views.TeamRemoveMembersView.as_view(),
        name='team-remove-members'),
    url(r'^games/', views.GamesView.as_view(),
        name='games'),
    url(r'^add_game/', views.GameAddView.as_view(),
        name='add-game'),
    url(r'^delete_games/', views.GamesDeleteView.as_view(),
        name='delete-games'),
    url(r'^add_cup/', views.CupAddView.as_view(),
        name='add-cup'),
    url(r'^cup_add_games/(?P<cup_id>(\d)+)', views.CupAddGamesView.as_view(),
        name='cup-add-games'),
    url(r'^knockout/(?P<tournament_id>(\d)+)/(?P<lap>(\d)+)/$', views.KnockoutView.as_view(),
        name='knockout'),
    url(r'^next_round/(?P<tournament_id>(\d)+)/(?P<lap>(\d)+)/$', views.knockout_next_round),
    url(r'^cup/(?P<cup_id>(\d)+)', views.CupView.as_view(),
        name='cup'),
    url(r'^cup/rank/(?P<cup_id>(\d)+)', views.CupRankView.as_view(),
        name='cupRank'),
    url(r'^cups_list/$', views.CupsListView.as_view(),
        name='cups'),
    url(r'^participations_add_to_game/(?P<tournament_id>(\d)+)', views.ParticipationsAddToGameView.as_view(),
        name='participations'),
    url(r'^team_add_to_game/(?P<tournament_id>(\d)+)', views.TeamsAddToGameView.as_view(),
        name='team-add-game'),
    url(r'^team_stats/(?P<team_id>(\d)+)', views.TeamDetailsStatsView.as_view(),
        name='team-stats'),
    url(r'^delete_cup/(?P<cup_id>(\d)+)', views.CupDeleteView.as_view(),
        name="cup-delete"),
]

spartakiada/models.py
from django.db import models
from django.urls import reverse


class Player(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('players')


    """
    Not perfect way to get players gender basing on their first name.
    Works only for polish names.
    """
    @property
    def gender(self):
        male_names = ["Bonawentura", "Kuba", "Kosma", "Attyla", "Barnaba", "Seba", "Dyzma", "Zawisza"]
        female_names = ["Miriam", "Nicole", "Noemi", "Beatrycze", "Nel"]
        name = self.name.partition(' ')[0]
        if name.endswith("a") and name not in male_names or name in female_names:
            return "F"
        else:
            return "M"



class Team(models.Model):
    name = models.CharField(max_length=128, unique=True)
    mates = models.ManyToManyField(Player, through='Member')

    def __str__(self):
        return '%s' % self.name


# enables players to be team members
class Member(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return '%s' % self.player.name


# allow us to use the same functions for players and teams
class Partaker(models.Model):
    player = models.ForeignKey(Player, null=True, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, null=True, on_delete=models.CASCADE)

    def __str__(self):
        if self.player:
            return self.player.name
        elif self.team:
            return self.team.name
        else:
            return "unknown partaker"

    @property
    # returns list of dictionaries made of duel-like objects
    def details(self):
        random_player = Player.objects.get(name="Random")
        random = Partaker.objects.get(player=random_player)
        participations = Participation.objects.filter(partaker=self)
        player_info = []
        if participations.count() != 0 and self != random:
            duels = []
            win = []
            for participation in participations:
                duels.append(Duel.objects.filter(player1=participation))
                duels.append(Duel.objects.filter(player2=participation))
            flat_duels = [item for sublist in duels for item in sublist]
            for duel in flat_duels:
                if duel.player1.partaker != random \
                        and duel.player2.partaker != random \
                        and duel.player1 != duel.player2:
                    player_info.append({
                        'player1': duel.player1.partaker,
                        'player2': duel.player2.partaker,
                        'points1': duel.points1,
                        'points2': duel.points2,
                        'game_name': duel.tournament.game.name,
                        'tournament_name': duel.tournament.cup.name,
                        'tournament_date': duel.tournament.cup.date,
                        'lap': duel.lap,
                    })
                elif duel.player1 == duel.player2:
                    win.append({
                        'player1': duel.player1.partaker,
                        'player2': duel.player2.partaker,
                        'points1': duel.points1,
                        'points2': duel.points2,
                        'game_name': duel.tournament.game.name,
                        'tournament_name': duel.tournament.cup.name,
                        'tournament_date': duel.tournament.cup.date,
                        'lap': duel.lap,
                    })
            # won objects are doubled, so we delete every second
            if len(win) > 0:
                del win[::2]

            # join both dictionaries
            player_info += win

        player_info = sorted(player_info, key=lambda k: k['tournament_date'], reverse=True)
        return player_info

    @property
    # returns dictionary
    def duels(self):
        player_info = self.details
        games_won = 0
        games_played = 0
        for duel in player_info:
            if duel['points1'] is not None:
                if duel['player1'] == self and duel['points1'] > duel['points2']:
                    games_won += 1
                    games_played += 1
                elif duel['player2'] == self and duel['points1'] < duel['points2']:
                    games_won += 1
                    games_played += 1
                else:
                    games_played += 1
        return {"won": games_won,
                "played": games_played}

    @property
    # returns list of duel objects
    def tournaments_won(self):
        player_info = self.details
        won_tournaments = []
        for duel in player_info:
            if duel['player1'] == duel['player2']:
                won_tournaments.append(duel)
        return won_tournaments

    @property
    # returns integer
    def was_second(self):
        silver_winners = []
        tournaments_participated = Tournament.objects.filter(participants=self)
        for tournaments in tournaments_participated:
            if tournaments.second is not None:
                silver_winners.append(tournaments.second.partaker)
        return silver_winners.count(self)

    @property
    # returns integer
    def tournaments_participated(self):
        participations = Participation.objects.filter(partaker=self)
        parts = []
        for part in participations:
            parts.append(part.tournament.cup.id)
        return len(set(parts))


# type of game/sport
class Game(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return '%s' % self.name


class Cup(models.Model):
    name = models.CharField(max_length=128)
    date = models.DateField()

    class Meta:
        unique_together = ("name", "date")

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('cup-add-games', kwargs={'cup_id': self.id})


class Tournament(models.Model):
    participants = models.ManyToManyField('Partaker', through='Participation')
    game = models.ForeignKey(Game, null=True, on_delete=models.CASCADE)
    cup = models.ForeignKey(Cup, null=True, on_delete=models.CASCADE)
    individual = models.BooleanField(default=True)

    class Meta:
        unique_together = ("cup", "game", "individual")

    @property
    # returns boolean value
    def is_over(self):
        duels = Duel.objects.filter(tournament=self).order_by("-lap")
        if duels[0].player1 is None:
            return False
        else:
            return True

    @property
    # returns duel object
    def winner(self):
        if self.is_over:
            duels = Duel.objects.filter(tournament=self).order_by("-lap")
            return duels[0]

    @property
    # returns participations object
    def second(self):
        if self.is_over:
            duels = Duel.objects.filter(tournament=self).order_by("-lap")
            if duels[0].player1 == duels[0].player2:
                if duels[1].player1 != duels[0].player1:
                    return duels[1].player1
                else:
                    return duels[1].player2

    @property
    # returns integer
    def last_lap(self):
        last_lap = Duel.objects.filter(tournament=self).last().lap
        return last_lap


class Participation(models.Model):
    partaker = models.ForeignKey(Partaker, null=True, on_delete=models.CASCADE)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)


# atomic event of all games, which is a single duel of two players
class Duel(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    player1 = models.ForeignKey(Participation, related_name='game_played', on_delete=models.CASCADE)
    player2 = models.ForeignKey(Participation, related_name='game_played2', on_delete=models.CASCADE)
    points1 = models.IntegerField(null=True)
    points2 = models.IntegerField(null=True)
    lap = models.IntegerField(null=True)


# model used for stats
class PlayerCache(models.Model):
    partaker = models.ForeignKey(Partaker, default=None, on_delete=models.CASCADE)
    won = models.IntegerField(null=True)
    played = models.IntegerField(null=True)
    tournament_won = models.IntegerField(null=True)
    tournament_second = models.IntegerField(null=True)
    tournament_participated = models.IntegerField(null=True)

spartakiada/views/base.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from spartakiada.models import Cup
from .player import *
from .team import *

class BaseView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(BaseView, self).dispatch(request, *args, **kwargs)

class AboutView(View):

    def get(self, request):
        return render(request, 'spartakiada/about_view.html')

# main page
class MenuView(View):

    def get(self, request):
        cup = Cup.objects.all().order_by("-date")
        players = best_players()
        teams = best_teams()
        ctx = {
            'cup': cup,
            'players': players,
            'teams': teams
        }
        return render(request, 'spartakiada/menu.html', ctx)

spartakiada/views/cup.py
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import CreateView, DeleteView, ListView
from spartakiada.models import Cup, Game, Tournament

class CupAddView(CreateView):
    model = Cup
    fields = [
        'name', 'date'
    ]

class CupAddGamesView(View):

    def get(self, request, cup_id):
        cup_id = int(cup_id)
        cup = Cup.objects.get(id=cup_id)
        game_list = Game.objects.all().order_by('name')
        tournament = Tournament.objects.filter(cup=cup)

        ctx = {
            'cup': cup,
            'game_list': game_list,
            'tournament': tournament
        }
        return render(request, 'spartakiada/cup_add_games_view.html', ctx)

    def post(self, request, cup_id):
        cup = Cup.objects.get(id=cup_id)
        for i in request.POST.getlist('game'):
            if 'ind_%s' % i in request.POST:
                Tournament.objects.create(cup=cup, game_id=i, individual=True)
            if 'team_%s' % i in request.POST:
                Tournament.objects.create(cup=cup, game_id=i, individual=False)
        tournaments = Tournament.objects.filter(cup=cup)
        if tournaments.count() != 0:
            return redirect('/cup/%s' % cup_id)
        else:
            return render(request, 'spartakiada/except_empty.html')


class CupView(View):

    def get(self, request, cup_id):
        cup = Cup.objects.get(id=cup_id)
        tournament_list = Tournament.objects.filter(cup=cup)
        ctx = {
            'cup': cup,
            'tournament_list': tournament_list,
        }
        if len(tournament_list) != 0:
            return render(request, 'spartakiada/cup_view.html', ctx)
        else:
            return redirect('/cup_add_games/%s' % cup_id)


class CupsListView(ListView):

    model = Cup

    ordering = ['-date']


class CupDeleteView(DeleteView):
    model = Cup
    success_url = '/'
    pk_url_kwarg = 'cup_id'

spartakiada/views/cupRank.py
from collections import OrderedDict
from django.shortcuts import redirect, render
from django.views import View
from spartakiada.models import Cup, Tournament, Participation, Duel

class CupRankView(View):
    
    def get(self, request, cup_id):
        try:
            cupScore = {}
            grandPrixList = []
            cup = Cup.objects.get(id=cup_id)
            tournament_list = Tournament.objects.filter(cup=cup)
            for tournament in tournament_list:
                participations = Participation.objects.filter(tournament=tournament)
                score = {}
                for participation in participations:
                    if Duel.objects.filter(tournament = tournament, player1 = participation).last():
                        duel_last = Duel.objects.filter(tournament = tournament, player1 = participation).last()
                    else:
                        duel_last = Duel.objects.filter(tournament = tournament, player2 = participation).last()
                    score[participation.partaker]=int(duel_last.lap - 1)
                scoreSorted = sorted(score.items(), key=lambda item: item[1], reverse=True)
                cupScore[tournament]=scoreSorted
                for val in scoreSorted:
                    grandPrixList.append(val)
            
            GPDict = {}
            for t in grandPrixList:
                if t[0] in GPDict:
                    GPDict[t[0]] = GPDict[t[0]]+t[1]
                else:
                    GPDict[t[0]] = t[1]
            GPDictSorted = sorted(GPDict.items(), key=lambda item: item[1], reverse=True)
            participationsCount = len(GPDictSorted)
            rangeCount = range(1, participationsCount+1)
            ctx = {
                'cup': cup,
                'tournament_list': tournament_list,
                'participations': participations,
                'cupScore': cupScore,
                'score': score,
                'scoreSorted': scoreSorted,
                'GPDict': GPDictSorted,
                'range': rangeCount 
            }
            return render(request, 'spartakiada/cupRank_view.html', ctx)
        except AttributeError:
            return render(request, 'spartakiada/except_option_disabled.html')

spartakiada/views/game.py
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import CreateView
from spartakiada.models import Game

class GamesView(View):
    
    def get(self, request):
        game_list = Game.objects.all().order_by('name')
        ctx = {
            'game_list': game_list
        }
        return render(request, 'spartakiada/game_view.html', ctx)


class GameAddView(CreateView):
    model = Game
    fields = [
        'name'
    ]
    success_url = '/games/'


class GamesDeleteView(View):

    def get(self, request):
        game_list = Game.objects.all().order_by('name')
        ctx = {
            'game_list': game_list,
        }
        return render(request, 'spartakiada/games_delete_view.html', ctx)

    def post(self, request):
        for i in request.POST.getlist('game'):
            game = Game.objects.filter(name=i)
            game.delete()
        return redirect('/games/')

spartakiada/templates/spartakiada/cupRank_view.html
{% extends 'spartakiada/base.html' %}
{% load pluralize_pl %}


{% block content %}

<h1 class="headtext" style="text-align: center; font-size: 2.5em; "><a class="maintext" href="/cup/{{ cup.id }}/">{{ cup.name }}</a></h1><hr>

    <div class="tableContainer">
    {% for key, value in cupScore.items %}
    <div class="tournamentTable">
    <table>
        <thead>
            <tr>
                <th colspan="2">{{key.game.name}}</th>
            </tr>
            <tr>
                <th>Zawodnik</th>
                <th>Punkty</th>
            </tr>
        </thead>
        <tbody>
            {% for k, val in value %}
                <tr>
                    <td>{{ k }}</td>
                    <td>{{ val }}</td>
                </tr>
            {% empty %}
                    <tr>
                        <td colspan="2">Dodaj zawodników do dyscypliny</td>
                    </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
    {% endfor %}
    </div>

<div class="GPTableContainer">
    <div class="grandPrixTable">
        <table>
            <thead>
                <tr>
                    <th colspan="2">GRAND PRIX</th>
                </tr>
                <tr>
                    <th>ZAWODNIK</th>
                    <th>PUNKTY</th>
                </tr>
            </thead>
            <tbody>
                <ol>
                {% for name, score in GPDict %}
                    <tr>
                        <td>{{ name }}</td>
                        <td>{{ score }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="2">Dodaj zawodników do danych dyscyplin</td>
                    </tr>
                {% endfor %}
                </ol>
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

spartakiada/templates/spartakiada/cup_add_games_view.html
{% extends 'spartakiada/base.html' %}

{% block content %}
    <h3 class="headtext">Dodaj dyscypliny do turnieju <a class="maintext">{{ cup }}</a></h3>

    <form action="" method="POST">{% csrf_token %}
        <h4><table class="tabcon">
            <tr class="maintext">
                <th style="text-align: center;"></th>
                <th style="text-align: center;">Wybierz</th>
                <th style="text-align: center;">I</th>
                <th style="text-align: center;">D</th>
            </tr>
        {% for game in game_list %}
            <tr>
                <th>{{ game.name }}</th>
                <td style="text-align: center;"><input class="checkbox" type='checkbox' name='game' value='{{ game.id }}'></td>
                <td style="text-align: center;"><input class="checkbox" type='checkbox' name='ind_{{ game.id }}' value='ind'></td>
                <td style="text-align: center;"><input class="checkbox" type='checkbox' name='team_{{ game.id }}' value='team'></td>
            </tr>
        {% empty %}
            <a id="link">BRAK DYSCYPLIN</a><br><br>
            <a href="{% url 'spartakiada:add-game' %}"
        class="toggle">
        &nbsp;DODAJ DYSYCPLINY&nbsp;</a>
        {% endfor %}
        </table></h4>
        <h5><br>I - rozgrywki indywidualne<br>D - rozgrywki drużynowe</h5>
        <br><input class="toggle" type="submit" value="&nbsp;DODAJ&nbsp;">
    </form>
{% endblock %}

spartakiada/templates/spartakiada/cup_form.html
{% extends 'spartakiada/base.html' %}

{% block content %}
    <div class="middleContainer">
        <div class="addContainer">
            <h3 class="headtext">Dodaj turniej</h3>
            <form action="" method="POST">{% csrf_token %}
                <h3 class="maintext">Nazwa: </h3>
                {{ form.name }}
                <h3 class="maintext">Data (rrrr-mm-dd): </h3>
                {{ form.date }}
                <br>{{ form.errors }}<br>
                <input class="toggle" type="submit" value="&nbsp;DODAJ&nbsp;">
            </form>
        </div>
    </div>
{% endblock %}

spartakiada/templates/spartakiada/cup_view.html
{% extends 'spartakiada/base.html' %}

{% block content %}

<h1 class="headtext" style="text-align: center; font-size: 2.5em; "><a class="maintext" href="/cup/{{ cup.id }}/">{{ cup.name }}</a></h1><hr>
    <br><br>
    <ol>
    {% for tournament in tournament_list %}
        {% if tournament.individual %}
            <a class="maintext"><li>{{ tournament.game }} I&nbsp;</a>
            {% if tournament.participants.count > 0 %}
                <a class="toggle" href="/knockout/{{ tournament.id }}/{{ tournament.last_lap }}">PRZEGLĄDAJ</a></li><br>
            {% else %}
                <a class="toggle" href="/participations_add_to_game/{{ tournament.id }}">DODAJ ZAWODNIKÓW</a></li><br>
            {% endif %}
        {% else %}
            <a class="maintext"><li>{{ tournament.game }} D&nbsp;</a>
            {% if tournament.participants.count > 0 %}
                <a class="toggle" href="/knockout/{{ tournament.id }}/{{ tournament.last_lap }}">PRZEGLĄDAJ</a></li><br>
            {% else %}
                <a class="toggle" href="/team_add_to_game/{{ tournament.id }}">DODAJ DRUŻYNY</a></li><br>
            {% endif %}
        {% endif %}
    {% endfor %}
    </ol>
    <br><br>
    <a class="toggle" href="/delete_cup/{{ cup.id }}/">&nbsp;USUŃ TURNIEJ&nbsp;</a>
    <a class="toggle" href="/cup/rank/{{ cup.id }}/">&nbsp;RANKING TURNIEJU&nbsp;</a>

{% endblock %}

spartakiada/templates/spartakiada/detail_view.html
{% block content %}

{% if partaker.was_second > 0 %}
        <div>
            <h4 class="maintext">
            {% if player.gender == "F" %}
                {{ player.name }} zajęła drugie miejsce
            {% elif partaker.team != null %}
                Drużyna była druga
            {% else %}
                {{ player.name }} zajął drugie miejsce
            {% endif %}

            {% if partaker.was_second == 1 %}
            raz.
            {% else %}
            {{partaker.was_second}} razy.
            {% endif %}
            </h4>
        </div>
        {% endif %}

    <br>
    <div><ol><h3 class="maintext" style="color: black;">Odbyte mecze:</h3><br>

    {% for info in partaker.details %}

        {% if info.player1 != info.player2 %}

        <li><a class="maintext">{{info.player1}} - {{info.player2}}</a> |

                {% if info.points1 is None %}

            <strong>wynik nieznany / mecz nierozstrzygniety</strong>

                {% else %}

            <strong>{{info.points1}} : {{info.points2}}</strong>

                {% endif %}

        <br>{{info.game_name}} (etap {{info.lap}}) na turnieju {{info.tournament_name}} ({{info.tournament_date}}) </li>


        {% endif %}
    <br>
        {% empty %}

        BRAK

    {% endfor %}

    </ol></div>

{% endblock %}

spartakiada/templates/spartakiada/except_cup_ended.html
{% extends 'spartakiada/base.html' %}

{% block content %}

    <br>
        <h1 class="headtext" style="text-align: center">ROZGRYWKI W TEJ DYSCYPLINIE ZOSTAŁY JUŻ ZAKOŃCZONE</h1><br>
        <div style="margin: 0 auto; text-align: center">
            <button class="toggle" onclick="goBack()">&nbsp;COFNIJ&nbsp;</button>
        </div>

<script>
function goBack() {
    window.history.back();
}
</script>
{% endblock %}

spartakiada/templates/spartakiada/except_option_disabled.html
{% extends 'spartakiada/base.html' %}

{% block content %}

    <br>
        <h1 class="headtext" style="text-align: center">TA OPCJA ZOSTAŁA WYŁĄCZONA Z POWODU WCZEŚNIEJSZYCH DZIAŁAŃ</h1><br>
        <div style="margin: 0 auto; text-align: center">
            <button class="toggle" onclick="goBack()">&nbsp;COFNIJ&nbsp;</button>
        </div>

<script>
function goBack() {
    window.history.back();
}
</script>
{% endblock %}

spartakiada/templates/spartakiada/games_delete_view.html
{% extends 'spartakiada/base.html' %}

{% block content %}

    <h3 class="headtext">Dyscypliny do usunięcia: </h3>
<form action="" method="POST">{% csrf_token %}
    <ol>
    {% for game in game_list %}
        <li style="align-items: center;"><a class="maintext">{{game}} <input class="checkbox" style="display: inherit; margin: 0;" type="checkbox"
            name="game" value="{{game}}"></a></li>
    {% endfor %}
    </ol>
    <input class="toggle" type="submit" value="&nbsp;USUŃ&nbsp;">
</form>


{% endblock %}

spartakiada/templates/spartakiada/knockout.html
{% extends 'spartakiada/base.html' %}

{% block content %}

<link rel="stylesheet" href="/static/spartakiada/style.css">


    <h1 class="headtext" style="text-align: center; font-size: 2.5em; "><a class="maintext" href="/cup/{{ tournament.cup.id }}/">{{ tournament.cup.name }}</a></h1><hr>
    <br><br>
<form action='#' method='POST'>
    {% csrf_token %}

    <h2 class="headtext">Dyscyplina <a class="maintext">{{tournament.game.name}}</a></h2><br>
        <div class="container"></div>

    {% for stage in stages %}
        {% if stage.player1.partaker == stage.player2.partaker %}
            <table class='{{stage.lap}}' id='win_bordered'>
                <tr>
                    <td class='nice {{stage.player1.partaker}}'><b>&nbsp;
                        {{stage.player1.partaker}}</b></td>
                </tr>
            <table>
        {% elif stage.lap|add:"0" == lap|add:"0" %}
            <table class="{{stage.lap}}" id="fight_bordered">

                <tr>
                    <td class="nice {{stage.player1.partaker}}">
                        &nbsp;{{stage.player1.partaker}}</td>
                    <td class="points"><input class="inputKO" type="number" name="{{stage.player1.partaker}}" value="{{stage.points1}}"></td>
                </tr>
                <tr>
                    <td class="nice {{stage.player2.partaker}}">
                        &nbsp;{{stage.player2.partaker}}</td>
                    <td class="points"><input class="inputKO" type="number" name="{{stage.player2.partaker}}" value="{{stage.points2}}"></td>
                </tr>

            </table>
        {% elif stage.lap|add:"0" != lap|add:"0" %}
            <table class="{{stage.lap}}">
                <tr>
                    <td class="nice {{stage.player1.partaker}}">&nbsp;
                        {{stage.player1.partaker}}</td>
                    <td class="points">{{stage.points1}}</td>
                </tr>
                <tr>
                    <td class="nice {{stage.player2.partaker}}">&nbsp;
                        {{stage.player2.partaker}}</td>
                    <td class="points">{{stage.points2}}</td>
                </tr>
            </table>
        {% else %}
        <p>Coś poszło nie tak</p>

        {% endif %}
    {% endfor %}
        <br><input class="toggle" type='submit' value='ZATWIERDŹ PUNKTY'>

</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/app.js"></script>
{% endblock %}

spartakiada/templates/spartakiada/teams_delete_view.html
{% extends 'spartakiada/base.html' %}

{% block content %}

    <h3 class="headtext">Drużyny do usunięcia: </h3>
<form action="" method="POST">{% csrf_token %}
    <ol>
    {% for team in team_list %}
        {% if team.name != "Random" %}
            <li style="align-items: center;"><a class="maintext">{{ team }} <input class="checkbox" style="display: inherit; margin: 0;" type="checkbox"
                name="team" value="{{ team }}"></a></li>
        {% endif %}
    {% endfor %}
    </ol>
    <input class="toggle" type="submit" value="&nbsp;USUŃ&nbsp;">
</form>

{% endblock %}